version: "2"

services:
  eos:
    build:
      context: ./eos
    image: eosio/eos
    command: /opt/eos/bin/start_eosd.sh
    ports:
      - ${HTTP_PORT}:8888
      - ${NODE_PORT}:9876
    expose:
      - "8888"
    volumes:
      - ./data-dir:/opt/eos/bin/data-dir

  walletd:
    image: eosio/eos
    command: /opt/eos/bin/eos-walletd
    links:
      - eos
    volumes:
      - ./data-dir:/opt/eos/bin/data-dir